

// ------------------------------------------------------------------------------------------------
// This code was generated by EntityFramework Reverse POCO Generator (http://www.reversepoco.com/).
// Created by Simon Hughes (https://about.me/simon.hughes).
//
// Do not make changes directly to this file - edit the template instead.
//
// The following connection settings were used to generate this file:
//     Configuration file:     "devinmajordotcom\Web.config"
//     Connection String Name: "MainDbConnection"
//     Connection String:      "Data Source=.\DEVINSSQLEXPRESS;Initial Catalog=devinmajordotcom;Integrated Security=True"
// ------------------------------------------------------------------------------------------------
// Database Edition       : Express Edition (64-bit)
// Database Engine Edition: Express

// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable EmptyNamespace
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace devinmajordotcom.Models
{
    using System.Linq;

    #region Unit of work

    public partial interface IdbContext : System.IDisposable
    {
        System.Data.Entity.DbSet<LandingPage_BannerLink> LandingPage_BannerLinks { get; set; } // BannerLink
        System.Data.Entity.DbSet<LandingPage_Config> LandingPage_Configs { get; set; } // Config
        System.Data.Entity.DbSet<LandingPage_SiteLink> LandingPage_SiteLinks { get; set; } // SiteLink
        System.Data.Entity.DbSet<MediaDashboard_SiteLink> MediaDashboard_SiteLinks { get; set; } // SiteLink
        System.Data.Entity.DbSet<MyHome_BlogPost> MyHome_BlogPosts { get; set; } // BlogPost
        System.Data.Entity.DbSet<MyHome_BlogPostComment> MyHome_BlogPostComments { get; set; } // BlogPostComment
        System.Data.Entity.DbSet<MyHome_SiteLink> MyHome_SiteLinks { get; set; } // SiteLink
        System.Data.Entity.DbSet<MyHome_UserConfig> MyHome_UserConfigs { get; set; } // UserConfig
        System.Data.Entity.DbSet<Portfolio_ContactLink> Portfolio_ContactLinks { get; set; } // ContactLink
        System.Data.Entity.DbSet<Portfolio_HighlightedSkill> Portfolio_HighlightedSkills { get; set; } // HighlightedSkill
        System.Data.Entity.DbSet<Portfolio_LanguageSkill> Portfolio_LanguageSkills { get; set; } // LanguageSkill
        System.Data.Entity.DbSet<Portfolio_PersonalDescription> Portfolio_PersonalDescriptions { get; set; } // PersonalDescription
        System.Data.Entity.DbSet<Portfolio_Profile> Portfolio_Profiles { get; set; } // Profile
        System.Data.Entity.DbSet<Portfolio_Project> Portfolio_Projects { get; set; } // Project
        System.Data.Entity.DbSet<Portfolio_ProjectType> Portfolio_ProjectTypes { get; set; } // ProjectType
        System.Data.Entity.DbSet<Portfolio_ProjectTypeMapping> Portfolio_ProjectTypeMappings { get; set; } // ProjectTypeMapping
        System.Data.Entity.DbSet<Portfolio_TechSkill> Portfolio_TechSkills { get; set; } // TechSkill
        System.Data.Entity.DbSet<RefactorLog> RefactorLogs { get; set; } // __RefactorLog
        System.Data.Entity.DbSet<Security_User> Security_Users { get; set; } // User

        int SaveChanges();
        System.Threading.Tasks.Task<int> SaveChangesAsync();
        System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken);
        System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get; }
        System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get; }
        System.Data.Entity.Database Database { get; }
        System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class;
        System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity);
        System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors();
        System.Data.Entity.DbSet Set(System.Type entityType);
        System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class;
        string ToString();
    }

    #endregion

    #region Database context

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class dbContext : System.Data.Entity.DbContext, IdbContext
    {
        public System.Data.Entity.DbSet<LandingPage_BannerLink> LandingPage_BannerLinks { get; set; } // BannerLink
        public System.Data.Entity.DbSet<LandingPage_Config> LandingPage_Configs { get; set; } // Config
        public System.Data.Entity.DbSet<LandingPage_SiteLink> LandingPage_SiteLinks { get; set; } // SiteLink
        public System.Data.Entity.DbSet<MediaDashboard_SiteLink> MediaDashboard_SiteLinks { get; set; } // SiteLink
        public System.Data.Entity.DbSet<MyHome_BlogPost> MyHome_BlogPosts { get; set; } // BlogPost
        public System.Data.Entity.DbSet<MyHome_BlogPostComment> MyHome_BlogPostComments { get; set; } // BlogPostComment
        public System.Data.Entity.DbSet<MyHome_SiteLink> MyHome_SiteLinks { get; set; } // SiteLink
        public System.Data.Entity.DbSet<MyHome_UserConfig> MyHome_UserConfigs { get; set; } // UserConfig
        public System.Data.Entity.DbSet<Portfolio_ContactLink> Portfolio_ContactLinks { get; set; } // ContactLink
        public System.Data.Entity.DbSet<Portfolio_HighlightedSkill> Portfolio_HighlightedSkills { get; set; } // HighlightedSkill
        public System.Data.Entity.DbSet<Portfolio_LanguageSkill> Portfolio_LanguageSkills { get; set; } // LanguageSkill
        public System.Data.Entity.DbSet<Portfolio_PersonalDescription> Portfolio_PersonalDescriptions { get; set; } // PersonalDescription
        public System.Data.Entity.DbSet<Portfolio_Profile> Portfolio_Profiles { get; set; } // Profile
        public System.Data.Entity.DbSet<Portfolio_Project> Portfolio_Projects { get; set; } // Project
        public System.Data.Entity.DbSet<Portfolio_ProjectType> Portfolio_ProjectTypes { get; set; } // ProjectType
        public System.Data.Entity.DbSet<Portfolio_ProjectTypeMapping> Portfolio_ProjectTypeMappings { get; set; } // ProjectTypeMapping
        public System.Data.Entity.DbSet<Portfolio_TechSkill> Portfolio_TechSkills { get; set; } // TechSkill
        public System.Data.Entity.DbSet<RefactorLog> RefactorLogs { get; set; } // __RefactorLog
        public System.Data.Entity.DbSet<Security_User> Security_Users { get; set; } // User

        static dbContext()
        {
            System.Data.Entity.Database.SetInitializer<dbContext>(null);
        }

        public dbContext()
            : base("Name=MainDbConnection")
        {
            InitializePartial();
        }

        public dbContext(string connectionString)
            : base(connectionString)
        {
            InitializePartial();
        }

        public dbContext(string connectionString, System.Data.Entity.Infrastructure.DbCompiledModel model)
            : base(connectionString, model)
        {
            InitializePartial();
        }

        public dbContext(System.Data.Common.DbConnection existingConnection, bool contextOwnsConnection)
            : base(existingConnection, contextOwnsConnection)
        {
            InitializePartial();
        }

        public dbContext(System.Data.Common.DbConnection existingConnection, System.Data.Entity.Infrastructure.DbCompiledModel model, bool contextOwnsConnection)
            : base(existingConnection, model, contextOwnsConnection)
        {
            InitializePartial();
        }

        protected override void Dispose(bool disposing)
        {
            base.Dispose(disposing);
        }

        public bool IsSqlParameterNull(System.Data.SqlClient.SqlParameter param)
        {
            var sqlValue = param.SqlValue;
            var nullableValue = sqlValue as System.Data.SqlTypes.INullable;
            if (nullableValue != null)
                return nullableValue.IsNull;
            return (sqlValue == null || sqlValue == System.DBNull.Value);
        }

        protected override void OnModelCreating(System.Data.Entity.DbModelBuilder modelBuilder)
        {
            base.OnModelCreating(modelBuilder);

            modelBuilder.Configurations.Add(new LandingPage_BannerLinkConfiguration());
            modelBuilder.Configurations.Add(new LandingPage_ConfigConfiguration());
            modelBuilder.Configurations.Add(new LandingPage_SiteLinkConfiguration());
            modelBuilder.Configurations.Add(new MediaDashboard_SiteLinkConfiguration());
            modelBuilder.Configurations.Add(new MyHome_BlogPostConfiguration());
            modelBuilder.Configurations.Add(new MyHome_BlogPostCommentConfiguration());
            modelBuilder.Configurations.Add(new MyHome_SiteLinkConfiguration());
            modelBuilder.Configurations.Add(new MyHome_UserConfigConfiguration());
            modelBuilder.Configurations.Add(new Portfolio_ContactLinkConfiguration());
            modelBuilder.Configurations.Add(new Portfolio_HighlightedSkillConfiguration());
            modelBuilder.Configurations.Add(new Portfolio_LanguageSkillConfiguration());
            modelBuilder.Configurations.Add(new Portfolio_PersonalDescriptionConfiguration());
            modelBuilder.Configurations.Add(new Portfolio_ProfileConfiguration());
            modelBuilder.Configurations.Add(new Portfolio_ProjectConfiguration());
            modelBuilder.Configurations.Add(new Portfolio_ProjectTypeConfiguration());
            modelBuilder.Configurations.Add(new Portfolio_ProjectTypeMappingConfiguration());
            modelBuilder.Configurations.Add(new Portfolio_TechSkillConfiguration());
            modelBuilder.Configurations.Add(new RefactorLogConfiguration());
            modelBuilder.Configurations.Add(new Security_UserConfiguration());

            OnModelCreatingPartial(modelBuilder);
        }

        public static System.Data.Entity.DbModelBuilder CreateModel(System.Data.Entity.DbModelBuilder modelBuilder, string schema)
        {
            modelBuilder.Configurations.Add(new LandingPage_BannerLinkConfiguration(schema));
            modelBuilder.Configurations.Add(new LandingPage_ConfigConfiguration(schema));
            modelBuilder.Configurations.Add(new LandingPage_SiteLinkConfiguration(schema));
            modelBuilder.Configurations.Add(new MediaDashboard_SiteLinkConfiguration(schema));
            modelBuilder.Configurations.Add(new MyHome_BlogPostConfiguration(schema));
            modelBuilder.Configurations.Add(new MyHome_BlogPostCommentConfiguration(schema));
            modelBuilder.Configurations.Add(new MyHome_SiteLinkConfiguration(schema));
            modelBuilder.Configurations.Add(new MyHome_UserConfigConfiguration(schema));
            modelBuilder.Configurations.Add(new Portfolio_ContactLinkConfiguration(schema));
            modelBuilder.Configurations.Add(new Portfolio_HighlightedSkillConfiguration(schema));
            modelBuilder.Configurations.Add(new Portfolio_LanguageSkillConfiguration(schema));
            modelBuilder.Configurations.Add(new Portfolio_PersonalDescriptionConfiguration(schema));
            modelBuilder.Configurations.Add(new Portfolio_ProfileConfiguration(schema));
            modelBuilder.Configurations.Add(new Portfolio_ProjectConfiguration(schema));
            modelBuilder.Configurations.Add(new Portfolio_ProjectTypeConfiguration(schema));
            modelBuilder.Configurations.Add(new Portfolio_ProjectTypeMappingConfiguration(schema));
            modelBuilder.Configurations.Add(new Portfolio_TechSkillConfiguration(schema));
            modelBuilder.Configurations.Add(new RefactorLogConfiguration(schema));
            modelBuilder.Configurations.Add(new Security_UserConfiguration(schema));
            return modelBuilder;
        }

        partial void InitializePartial();
        partial void OnModelCreatingPartial(System.Data.Entity.DbModelBuilder modelBuilder);
    }
    #endregion

    #region Database context factory

    public class dbContextFactory : System.Data.Entity.Infrastructure.IDbContextFactory<dbContext>
    {
        public dbContext Create()
        {
            return new dbContext();
        }
    }

    #endregion

    #region Fake Database context

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class FakedbContext : IdbContext
    {
        public System.Data.Entity.DbSet<LandingPage_BannerLink> LandingPage_BannerLinks { get; set; }
        public System.Data.Entity.DbSet<LandingPage_Config> LandingPage_Configs { get; set; }
        public System.Data.Entity.DbSet<LandingPage_SiteLink> LandingPage_SiteLinks { get; set; }
        public System.Data.Entity.DbSet<MediaDashboard_SiteLink> MediaDashboard_SiteLinks { get; set; }
        public System.Data.Entity.DbSet<MyHome_BlogPost> MyHome_BlogPosts { get; set; }
        public System.Data.Entity.DbSet<MyHome_BlogPostComment> MyHome_BlogPostComments { get; set; }
        public System.Data.Entity.DbSet<MyHome_SiteLink> MyHome_SiteLinks { get; set; }
        public System.Data.Entity.DbSet<MyHome_UserConfig> MyHome_UserConfigs { get; set; }
        public System.Data.Entity.DbSet<Portfolio_ContactLink> Portfolio_ContactLinks { get; set; }
        public System.Data.Entity.DbSet<Portfolio_HighlightedSkill> Portfolio_HighlightedSkills { get; set; }
        public System.Data.Entity.DbSet<Portfolio_LanguageSkill> Portfolio_LanguageSkills { get; set; }
        public System.Data.Entity.DbSet<Portfolio_PersonalDescription> Portfolio_PersonalDescriptions { get; set; }
        public System.Data.Entity.DbSet<Portfolio_Profile> Portfolio_Profiles { get; set; }
        public System.Data.Entity.DbSet<Portfolio_Project> Portfolio_Projects { get; set; }
        public System.Data.Entity.DbSet<Portfolio_ProjectType> Portfolio_ProjectTypes { get; set; }
        public System.Data.Entity.DbSet<Portfolio_ProjectTypeMapping> Portfolio_ProjectTypeMappings { get; set; }
        public System.Data.Entity.DbSet<Portfolio_TechSkill> Portfolio_TechSkills { get; set; }
        public System.Data.Entity.DbSet<RefactorLog> RefactorLogs { get; set; }
        public System.Data.Entity.DbSet<Security_User> Security_Users { get; set; }

        public FakedbContext()
        {
            LandingPage_BannerLinks = new FakeDbSet<LandingPage_BannerLink>("Id");
            LandingPage_Configs = new FakeDbSet<LandingPage_Config>("Id");
            LandingPage_SiteLinks = new FakeDbSet<LandingPage_SiteLink>("Id");
            MediaDashboard_SiteLinks = new FakeDbSet<MediaDashboard_SiteLink>("Id");
            MyHome_BlogPosts = new FakeDbSet<MyHome_BlogPost>("Id");
            MyHome_BlogPostComments = new FakeDbSet<MyHome_BlogPostComment>("Id");
            MyHome_SiteLinks = new FakeDbSet<MyHome_SiteLink>("Id");
            MyHome_UserConfigs = new FakeDbSet<MyHome_UserConfig>("Id");
            Portfolio_ContactLinks = new FakeDbSet<Portfolio_ContactLink>("Id");
            Portfolio_HighlightedSkills = new FakeDbSet<Portfolio_HighlightedSkill>("Id");
            Portfolio_LanguageSkills = new FakeDbSet<Portfolio_LanguageSkill>("Id");
            Portfolio_PersonalDescriptions = new FakeDbSet<Portfolio_PersonalDescription>("Id");
            Portfolio_Profiles = new FakeDbSet<Portfolio_Profile>("Id");
            Portfolio_Projects = new FakeDbSet<Portfolio_Project>("Id");
            Portfolio_ProjectTypes = new FakeDbSet<Portfolio_ProjectType>("Id");
            Portfolio_ProjectTypeMappings = new FakeDbSet<Portfolio_ProjectTypeMapping>("Id");
            Portfolio_TechSkills = new FakeDbSet<Portfolio_TechSkill>("Id");
            RefactorLogs = new FakeDbSet<RefactorLog>("OperationKey");
            Security_Users = new FakeDbSet<Security_User>("Id");

            InitializePartial();
        }

        public int SaveChangesCount { get; private set; }
        public int SaveChanges()
        {
            ++SaveChangesCount;
            return 1;
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync()
        {
            ++SaveChangesCount;
            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1);
        }

        public System.Threading.Tasks.Task<int> SaveChangesAsync(System.Threading.CancellationToken cancellationToken)
        {
            ++SaveChangesCount;
            return System.Threading.Tasks.Task<int>.Factory.StartNew(() => 1, cancellationToken);
        }

        partial void InitializePartial();

        protected virtual void Dispose(bool disposing)
        {
        }

        public void Dispose()
        {
            Dispose(true);
        }

        private System.Data.Entity.Infrastructure.DbChangeTracker _changeTracker;
        public System.Data.Entity.Infrastructure.DbChangeTracker ChangeTracker { get { return _changeTracker; } }
        private System.Data.Entity.Infrastructure.DbContextConfiguration _configuration;
        public System.Data.Entity.Infrastructure.DbContextConfiguration Configuration { get { return _configuration; } }
        private System.Data.Entity.Database _database;
        public System.Data.Entity.Database Database { get { return _database; } }
        public System.Data.Entity.Infrastructure.DbEntityEntry<TEntity> Entry<TEntity>(TEntity entity) where TEntity : class
        {
            throw new System.NotImplementedException();
        }
        public System.Data.Entity.Infrastructure.DbEntityEntry Entry(object entity)
        {
            throw new System.NotImplementedException();
        }
        public System.Collections.Generic.IEnumerable<System.Data.Entity.Validation.DbEntityValidationResult> GetValidationErrors()
        {
            throw new System.NotImplementedException();
        }
        public System.Data.Entity.DbSet Set(System.Type entityType)
        {
            throw new System.NotImplementedException();
        }
        public System.Data.Entity.DbSet<TEntity> Set<TEntity>() where TEntity : class
        {
            throw new System.NotImplementedException();
        }
        public override string ToString()
        {
            throw new System.NotImplementedException();
        }

    }

    // ************************************************************************
    // Fake DbSet
    // Implementing Find:
    //      The Find method is difficult to implement in a generic fashion. If
    //      you need to test code that makes use of the Find method it is
    //      easiest to create a test DbSet for each of the entity types that
    //      need to support find. You can then write logic to find that
    //      particular type of entity, as shown below:
    //      public class FakeBlogDbSet : FakeDbSet<Blog>
    //      {
    //          public override Blog Find(params object[] keyValues)
    //          {
    //              var id = (int) keyValues.Single();
    //              return this.SingleOrDefault(b => b.BlogId == id);
    //          }
    //      }
    //      Read more about it here: https://msdn.microsoft.com/en-us/data/dn314431.aspx
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class FakeDbSet<TEntity> : System.Data.Entity.DbSet<TEntity>, IQueryable, System.Collections.Generic.IEnumerable<TEntity>, System.Data.Entity.Infrastructure.IDbAsyncEnumerable<TEntity> where TEntity : class
    {
        private readonly System.Reflection.PropertyInfo[] _primaryKeys;
        private readonly System.Collections.ObjectModel.ObservableCollection<TEntity> _data;
        private readonly IQueryable _query;

        public FakeDbSet()
        {
            _data = new System.Collections.ObjectModel.ObservableCollection<TEntity>();
            _query = _data.AsQueryable();

            InitializePartial();
        }

        public FakeDbSet(params string[] primaryKeys)
        {
            _primaryKeys = typeof(TEntity).GetProperties().Where(x => primaryKeys.Contains(x.Name)).ToArray();
            _data = new System.Collections.ObjectModel.ObservableCollection<TEntity>();
            _query = _data.AsQueryable();

            InitializePartial();
        }

        public override TEntity Find(params object[] keyValues)
        {
            if (_primaryKeys == null)
                throw new System.ArgumentException("No primary keys defined");
            if (keyValues.Length != _primaryKeys.Length)
                throw new System.ArgumentException("Incorrect number of keys passed to Find method");

            var keyQuery = this.AsQueryable();
            keyQuery = keyValues
                .Select((t, i) => i)
                .Aggregate(keyQuery,
                    (current, x) =>
                        current.Where(entity => _primaryKeys[x].GetValue(entity, null).Equals(keyValues[x])));

            return keyQuery.SingleOrDefault();
        }

        public override System.Threading.Tasks.Task<TEntity> FindAsync(System.Threading.CancellationToken cancellationToken, params object[] keyValues)
        {
            return System.Threading.Tasks.Task<TEntity>.Factory.StartNew(() => Find(keyValues), cancellationToken);
        }

        public override System.Threading.Tasks.Task<TEntity> FindAsync(params object[] keyValues)
        {
            return System.Threading.Tasks.Task<TEntity>.Factory.StartNew(() => Find(keyValues));
        }

        public override System.Collections.Generic.IEnumerable<TEntity> AddRange(System.Collections.Generic.IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new System.ArgumentNullException("entities");
            var items = entities.ToList();
            foreach (var entity in items)
            {
                _data.Add(entity);
            }
            return items;
        }

        public override TEntity Add(TEntity item)
        {
            if (item == null) throw new System.ArgumentNullException("item");
            _data.Add(item);
            return item;
        }

        public override System.Collections.Generic.IEnumerable<TEntity> RemoveRange(System.Collections.Generic.IEnumerable<TEntity> entities)
        {
            if (entities == null) throw new System.ArgumentNullException("entities");
            var items = entities.ToList();
            foreach (var entity in items)
            {
                _data.Remove(entity);
            }
            return items;
        }

        public override TEntity Remove(TEntity item)
        {
            if (item == null) throw new System.ArgumentNullException("item");
            _data.Remove(item);
            return item;
        }

        public override TEntity Attach(TEntity item)
        {
            if (item == null) throw new System.ArgumentNullException("item");
            _data.Add(item);
            return item;
        }

        public override TEntity Create()
        {
            return System.Activator.CreateInstance<TEntity>();
        }

        public override TDerivedEntity Create<TDerivedEntity>()
        {
            return System.Activator.CreateInstance<TDerivedEntity>();
        }

        public override System.Collections.ObjectModel.ObservableCollection<TEntity> Local
        {
            get { return _data; }
        }

        System.Type IQueryable.ElementType
        {
            get { return _query.ElementType; }
        }

        System.Linq.Expressions.Expression IQueryable.Expression
        {
            get { return _query.Expression; }
        }

        IQueryProvider IQueryable.Provider
        {
            get { return new FakeDbAsyncQueryProvider<TEntity>(_query.Provider); }
        }

        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        System.Collections.Generic.IEnumerator<TEntity> System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator()
        {
            return _data.GetEnumerator();
        }

        System.Data.Entity.Infrastructure.IDbAsyncEnumerator<TEntity> System.Data.Entity.Infrastructure.IDbAsyncEnumerable<TEntity>.GetAsyncEnumerator()
        {
            return new FakeDbAsyncEnumerator<TEntity>(_data.GetEnumerator());
        }

        partial void InitializePartial();
    }

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class FakeDbAsyncQueryProvider<TEntity> : System.Data.Entity.Infrastructure.IDbAsyncQueryProvider
    {
        private readonly IQueryProvider _inner;

        public FakeDbAsyncQueryProvider(IQueryProvider inner)
        {
            _inner = inner;
        }

        public IQueryable CreateQuery(System.Linq.Expressions.Expression expression)
        {
            return new FakeDbAsyncEnumerable<TEntity>(expression);
        }

        public IQueryable<TElement> CreateQuery<TElement>(System.Linq.Expressions.Expression expression)
        {
            return new FakeDbAsyncEnumerable<TElement>(expression);
        }

        public object Execute(System.Linq.Expressions.Expression expression)
        {
            return _inner.Execute(expression);
        }

        public TResult Execute<TResult>(System.Linq.Expressions.Expression expression)
        {
            return _inner.Execute<TResult>(expression);
        }

        public System.Threading.Tasks.Task<object> ExecuteAsync(System.Linq.Expressions.Expression expression, System.Threading.CancellationToken cancellationToken)
        {
            return System.Threading.Tasks.Task.FromResult(Execute(expression));
        }

        public System.Threading.Tasks.Task<TResult> ExecuteAsync<TResult>(System.Linq.Expressions.Expression expression, System.Threading.CancellationToken cancellationToken)
        {
            return System.Threading.Tasks.Task.FromResult(Execute<TResult>(expression));
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class FakeDbAsyncEnumerable<T> : EnumerableQuery<T>, System.Data.Entity.Infrastructure.IDbAsyncEnumerable<T>, IQueryable<T>
    {
        public FakeDbAsyncEnumerable(System.Collections.Generic.IEnumerable<T> enumerable)
            : base(enumerable)
        { }

        public FakeDbAsyncEnumerable(System.Linq.Expressions.Expression expression)
            : base(expression)
        { }

        public System.Data.Entity.Infrastructure.IDbAsyncEnumerator<T> GetAsyncEnumerator()
        {
            return new FakeDbAsyncEnumerator<T>(this.AsEnumerable().GetEnumerator());
        }

        System.Data.Entity.Infrastructure.IDbAsyncEnumerator System.Data.Entity.Infrastructure.IDbAsyncEnumerable.GetAsyncEnumerator()
        {
            return GetAsyncEnumerator();
        }

        IQueryProvider IQueryable.Provider
        {
            get { return new FakeDbAsyncQueryProvider<T>(this); }
        }
    }

    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public class FakeDbAsyncEnumerator<T> : System.Data.Entity.Infrastructure.IDbAsyncEnumerator<T>
    {
        private readonly System.Collections.Generic.IEnumerator<T> _inner;

        public FakeDbAsyncEnumerator(System.Collections.Generic.IEnumerator<T> inner)
        {
            _inner = inner;
        }

        public void Dispose()
        {
            _inner.Dispose();
        }

        public System.Threading.Tasks.Task<bool> MoveNextAsync(System.Threading.CancellationToken cancellationToken)
        {
            return System.Threading.Tasks.Task.FromResult(_inner.MoveNext());
        }

        public T Current
        {
            get { return _inner.Current; }
        }

        object System.Data.Entity.Infrastructure.IDbAsyncEnumerator.Current
        {
            get { return Current; }
        }
    }

    #endregion

    #region POCO classes

    // BannerLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class LandingPage_BannerLink
    {
        public int Id { get; set; } // ID (Primary key)
        public string DisplayName { get; set; } // DisplayName (length: 50)
        public string Description { get; set; } // Description (length: 500)
        public string Directive { get; set; } // Directive (length: 100)
        public string Url { get; set; } // URL (length: 500)
        public string Action { get; set; } // Action (length: 500)
        public string Controller { get; set; } // Controller (length: 500)
        public string DisplayIcon { get; set; } // DisplayIcon (length: 500)
        public bool IsDefault { get; set; } // IsDefault
        public bool IsEnabled { get; set; } // IsEnabled
        public int? Order { get; set; } // Order
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        public LandingPage_BannerLink()
        {
            IsDefault = false;
            IsEnabled = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // Config
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class LandingPage_Config
    {
        public int Id { get; set; } // Id (Primary key)
        public string AppsTitle { get; set; } // AppsTitle
        public string AppsIntro { get; set; } // AppsIntro
        public string AppsDescription { get; set; } // AppsDescription
        public string ContactTitle { get; set; } // ContactTitle
        public string ContactInstructions { get; set; } // ContactInstructions
        public string ServerStatusTitle { get; set; } // ServerStatusTitle
        public string ServerStatusDescription { get; set; } // ServerStatusDescription
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        public LandingPage_Config()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // SiteLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class LandingPage_SiteLink
    {
        public int Id { get; set; } // ID (Primary key)
        public string DisplayName { get; set; } // DisplayName (length: 50)
        public string Description { get; set; } // Description (length: 500)
        public string Directive { get; set; } // Directive (length: 100)
        public string Url { get; set; } // URL (length: 500)
        public string Action { get; set; } // Action (length: 500)
        public string Controller { get; set; } // Controller (length: 500)
        public string DisplayIcon { get; set; } // DisplayIcon (length: 500)
        public bool IsDefault { get; set; } // IsDefault
        public bool IsEnabled { get; set; } // IsEnabled
        public int? Order { get; set; } // Order
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        public LandingPage_SiteLink()
        {
            IsDefault = false;
            IsEnabled = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // SiteLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class MediaDashboard_SiteLink
    {
        public int Id { get; set; } // ID (Primary key)
        public string DisplayName { get; set; } // DisplayName (length: 50)
        public string Description { get; set; } // Description (length: 500)
        public string Directive { get; set; } // Directive (length: 100)
        public string Url { get; set; } // URL (length: 500)
        public string Action { get; set; } // Action (length: 500)
        public string Controller { get; set; } // Controller (length: 500)
        public string DisplayIcon { get; set; } // DisplayIcon (length: 500)
        public bool IsDefault { get; set; } // IsDefault
        public bool IsEnabled { get; set; } // IsEnabled
        public bool IsPublic { get; set; } // IsPublic
        public int? Order { get; set; } // Order
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        public MediaDashboard_SiteLink()
        {
            IsDefault = false;
            IsEnabled = true;
            IsPublic = false;
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // BlogPost
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class MyHome_BlogPost
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserId { get; set; } // UserID
        public byte[] Image { get; set; } // Image
        public string Title { get; set; } // Title
        public string Body { get; set; } // Body
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        // Foreign keys

        /// <summary>
        /// Parent Security_User pointed by [BlogPost].([UserId]) (MyHome_BlogPost_UserID_Security_User_Id)
        /// </summary>
        public virtual Security_User Security_User { get; set; } // MyHome_BlogPost_UserID_Security_User_Id

        public MyHome_BlogPost()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // BlogPostComment
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class MyHome_BlogPostComment
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserId { get; set; } // UserID
        public string CommentBody { get; set; } // CommentBody
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        // Foreign keys

        /// <summary>
        /// Parent Security_User pointed by [BlogPostComment].([UserId]) (MyHome_BlogPostComment_UserID_Security_User_Id)
        /// </summary>
        public virtual Security_User Security_User { get; set; } // MyHome_BlogPostComment_UserID_Security_User_Id

        public MyHome_BlogPostComment()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // SiteLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class MyHome_SiteLink
    {
        public int Id { get; set; } // ID (Primary key)
        public int UserId { get; set; } // UserID
        public string DisplayName { get; set; } // DisplayName (length: 50)
        public string Description { get; set; } // Description (length: 500)
        public string Directive { get; set; } // Directive (length: 100)
        public string Url { get; set; } // URL (length: 500)
        public string Action { get; set; } // Action (length: 500)
        public string Controller { get; set; } // Controller (length: 500)
        public string DisplayIcon { get; set; } // DisplayIcon (length: 500)
        public bool IsDefault { get; set; } // IsDefault
        public bool IsEnabled { get; set; } // IsEnabled
        public byte[] Image { get; set; } // Image
        public int? Order { get; set; } // Order
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        // Foreign keys

        /// <summary>
        /// Parent Security_User pointed by [SiteLink].([UserId]) (MyHome_SiteLink_UserID_Security_User_Id)
        /// </summary>
        public virtual Security_User Security_User { get; set; } // MyHome_SiteLink_UserID_Security_User_Id

        public MyHome_SiteLink()
        {
            IsDefault = false;
            IsEnabled = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // UserConfig
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class MyHome_UserConfig
    {
        public int Id { get; set; } // Id (Primary key)
        public int UserId { get; set; } // UserID
        public bool ShowDateAndTime { get; set; } // ShowDateAndTime
        public bool ShowWeather { get; set; } // ShowWeather
        public bool ShowBanner { get; set; } // ShowBanner
        public bool ShowBookmarks { get; set; } // ShowBookmarks
        public bool ShowBlog { get; set; } // ShowBlog
        public string BookmarksTitle { get; set; } // BookmarksTitle
        public string Greeting { get; set; } // Greeting
        public string BlogTitle { get; set; } // BlogTitle
        public byte[] BackgroundImage { get; set; } // BackgroundImage
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        // Foreign keys

        /// <summary>
        /// Parent Security_User pointed by [UserConfig].([UserId]) (MyHome_UserHomeConfig_UserId_Security_User_ID)
        /// </summary>
        public virtual Security_User Security_User { get; set; } // MyHome_UserHomeConfig_UserId_Security_User_ID

        public MyHome_UserConfig()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ContactLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_ContactLink
    {
        public int Id { get; set; } // ID (Primary key)
        public string DisplayName { get; set; } // DisplayName (length: 50)
        public string Description { get; set; } // Description (length: 500)
        public string Directive { get; set; } // Directive (length: 100)
        public string Url { get; set; } // URL (length: 500)
        public string Action { get; set; } // Action (length: 500)
        public string Controller { get; set; } // Controller (length: 500)
        public string DisplayIcon { get; set; } // DisplayIcon (length: 500)
        public bool IsDefault { get; set; } // IsDefault
        public bool IsEnabled { get; set; } // IsEnabled
        public int? Order { get; set; } // Order
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        public Portfolio_ContactLink()
        {
            IsDefault = false;
            IsEnabled = true;
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // HighlightedSkill
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_HighlightedSkill
    {
        public int Id { get; set; } // ID (Primary key)
        public string Description { get; set; } // Description (length: 500)
        public string DisplayName { get; set; } // DisplayName (length: 100)
        public int? ProficiencyPercentage { get; set; } // ProficiencyPercentage
        public string DisplayIcon { get; set; } // DisplayIcon (length: 100)
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        public Portfolio_HighlightedSkill()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // LanguageSkill
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_LanguageSkill
    {
        public int Id { get; set; } // ID (Primary key)
        public string Description { get; set; } // Description (length: 500)
        public string DisplayName { get; set; } // DisplayName (length: 100)
        public int? ProficiencyPercentage { get; set; } // ProficiencyPercentage
        public string DisplayIcon { get; set; } // DisplayIcon (length: 100)
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        public Portfolio_LanguageSkill()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // PersonalDescription
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_PersonalDescription
    {
        public int Id { get; set; } // ID (Primary key)
        public string Adjective1 { get; set; } // Adjective1 (length: 100)
        public string Adjective2 { get; set; } // Adjective2 (length: 100)
        public string Adjective3 { get; set; } // Adjective3 (length: 100)
        public string Blurb { get; set; } // Blurb
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        public Portfolio_PersonalDescription()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // Profile
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_Profile
    {
        public int Id { get; set; } // ID (Primary key)
        public string FirstName { get; set; } // FirstName (length: 100)
        public string LastName { get; set; } // LastName (length: 100)
        public System.DateTime DateOfBirth { get; set; } // DateOfBirth
        public string Address { get; set; } // Address (length: 100)
        public string PhoneNumber { get; set; } // PhoneNumber (length: 25)
        public string EmailAddress { get; set; } // EmailAddress (length: 200)
        public string PositionTitle { get; set; } // PositionTitle (length: 100)
        public string PersonalDescription { get; set; } // PersonalDescription (length: 500)
        public string WebsiteText { get; set; } // WebsiteText (length: 100)
        public string WebsiteUrl { get; set; } // WebsiteURL (length: 200)
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        public Portfolio_Profile()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // Project
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_Project
    {
        public int Id { get; set; } // ID (Primary key)
        public string Name { get; set; } // Name (length: 100)
        public string Description { get; set; } // Description (length: 500)
        public byte[] Image { get; set; } // Image
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        // Reverse navigation

        /// <summary>
        /// Child Portfolio_ProjectTypeMappings where [ProjectTypeMapping].[ProjectID] point to this entity (ProjectTypeMapping_ProjectID_Project_ID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Portfolio_ProjectTypeMapping> Portfolio_ProjectTypeMappings { get; set; } // ProjectTypeMapping.ProjectTypeMapping_ProjectID_Project_ID

        public Portfolio_Project()
        {
            Portfolio_ProjectTypeMappings = new System.Collections.Generic.List<Portfolio_ProjectTypeMapping>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ProjectType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_ProjectType
    {
        public int Id { get; set; } // ID (Primary key)
        public string Type { get; set; } // Type (length: 100)
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        // Reverse navigation

        /// <summary>
        /// Child Portfolio_ProjectTypeMappings where [ProjectTypeMapping].[ProjectTypeID] point to this entity (ProjectTypeMapping_ProjectTypeID_ProjectType_ID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<Portfolio_ProjectTypeMapping> Portfolio_ProjectTypeMappings { get; set; } // ProjectTypeMapping.ProjectTypeMapping_ProjectTypeID_ProjectType_ID

        public Portfolio_ProjectType()
        {
            Portfolio_ProjectTypeMappings = new System.Collections.Generic.List<Portfolio_ProjectTypeMapping>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // ProjectTypeMapping
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_ProjectTypeMapping
    {
        public int Id { get; set; } // ID (Primary key)
        public int ProjectId { get; set; } // ProjectID
        public int ProjectTypeId { get; set; } // ProjectTypeID
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        // Foreign keys

        /// <summary>
        /// Parent Portfolio_Project pointed by [ProjectTypeMapping].([ProjectId]) (ProjectTypeMapping_ProjectID_Project_ID)
        /// </summary>
        public virtual Portfolio_Project Portfolio_Project { get; set; } // ProjectTypeMapping_ProjectID_Project_ID

        /// <summary>
        /// Parent Portfolio_ProjectType pointed by [ProjectTypeMapping].([ProjectTypeId]) (ProjectTypeMapping_ProjectTypeID_ProjectType_ID)
        /// </summary>
        public virtual Portfolio_ProjectType Portfolio_ProjectType { get; set; } // ProjectTypeMapping_ProjectTypeID_ProjectType_ID

        public Portfolio_ProjectTypeMapping()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // TechSkill
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_TechSkill
    {
        public int Id { get; set; } // ID (Primary key)
        public string Description { get; set; } // Description (length: 500)
        public string DisplayName { get; set; } // DisplayName (length: 100)
        public int? ProficiencyPercentage { get; set; } // ProficiencyPercentage
        public string DisplayIcon { get; set; } // DisplayIcon (length: 100)
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        public Portfolio_TechSkill()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // __RefactorLog
    ///<summary>
    /// refactoring log
    ///</summary>
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class RefactorLog
    {
        public System.Guid OperationKey { get; set; } // OperationKey (Primary key)
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        public RefactorLog()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

    // User
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Security_User
    {
        public int Id { get; set; } // ID (Primary key)
        public string ClientName { get; set; } // ClientName (length: 500)
        public bool IsActive { get; set; } // IsActive
        public string EmailAddress { get; set; } // EmailAddress (length: 250)
        public bool IsAdmin { get; set; } // IsAdmin
        public string UserName { get; set; } // UserName
        public string Password { get; set; } // Password
        public System.Guid Guid { get; set; } // GUID
        public System.DateTime? CreatedOn { get; set; } // CreatedOn
        public string CreatedBy { get; set; } // CreatedBy
        public System.DateTime? ModifiedOn { get; set; } // ModifiedOn
        public string ModifiedBy { get; set; } // ModifiedBy

        // Reverse navigation

        /// <summary>
        /// Child MyHome_BlogPosts where [BlogPost].[UserID] point to this entity (MyHome_BlogPost_UserID_Security_User_Id)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<MyHome_BlogPost> MyHome_BlogPosts { get; set; } // BlogPost.MyHome_BlogPost_UserID_Security_User_Id
        /// <summary>
        /// Child MyHome_BlogPostComments where [BlogPostComment].[UserID] point to this entity (MyHome_BlogPostComment_UserID_Security_User_Id)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<MyHome_BlogPostComment> MyHome_BlogPostComments { get; set; } // BlogPostComment.MyHome_BlogPostComment_UserID_Security_User_Id
        /// <summary>
        /// Child MyHome_SiteLinks where [SiteLink].[UserID] point to this entity (MyHome_SiteLink_UserID_Security_User_Id)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<MyHome_SiteLink> MyHome_SiteLinks { get; set; } // SiteLink.MyHome_SiteLink_UserID_Security_User_Id
        /// <summary>
        /// Child MyHome_UserConfigs where [UserConfig].[UserID] point to this entity (MyHome_UserHomeConfig_UserId_Security_User_ID)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<MyHome_UserConfig> MyHome_UserConfigs { get; set; } // UserConfig.MyHome_UserHomeConfig_UserId_Security_User_ID

        public Security_User()
        {
            IsActive = true;
            IsAdmin = false;
            MyHome_BlogPosts = new System.Collections.Generic.List<MyHome_BlogPost>();
            MyHome_BlogPostComments = new System.Collections.Generic.List<MyHome_BlogPostComment>();
            MyHome_SiteLinks = new System.Collections.Generic.List<MyHome_SiteLink>();
            MyHome_UserConfigs = new System.Collections.Generic.List<MyHome_UserConfig>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

    #endregion

    #region POCO Configuration

    // BannerLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class LandingPage_BannerLinkConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LandingPage_BannerLink>
    {
        public LandingPage_BannerLinkConfiguration()
            : this("LandingPage")
        {
        }

        public LandingPage_BannerLinkConfiguration(string schema)
        {
            ToTable("BannerLink", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DisplayName).HasColumnName(@"DisplayName").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Directive).HasColumnName(@"Directive").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.Url).HasColumnName(@"URL").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Action).HasColumnName(@"Action").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Controller).HasColumnName(@"Controller").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.DisplayIcon).HasColumnName(@"DisplayIcon").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.IsDefault).HasColumnName(@"IsDefault").HasColumnType("bit").IsRequired();
            Property(x => x.IsEnabled).HasColumnName(@"IsEnabled").HasColumnType("bit").IsRequired();
            Property(x => x.Order).HasColumnName(@"Order").HasColumnType("int").IsOptional();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // Config
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class LandingPage_ConfigConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LandingPage_Config>
    {
        public LandingPage_ConfigConfiguration()
            : this("LandingPage")
        {
        }

        public LandingPage_ConfigConfiguration(string schema)
        {
            ToTable("Config", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.AppsTitle).HasColumnName(@"AppsTitle").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.AppsIntro).HasColumnName(@"AppsIntro").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.AppsDescription).HasColumnName(@"AppsDescription").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ContactTitle).HasColumnName(@"ContactTitle").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ContactInstructions).HasColumnName(@"ContactInstructions").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ServerStatusTitle).HasColumnName(@"ServerStatusTitle").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ServerStatusDescription).HasColumnName(@"ServerStatusDescription").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // SiteLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class LandingPage_SiteLinkConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<LandingPage_SiteLink>
    {
        public LandingPage_SiteLinkConfiguration()
            : this("LandingPage")
        {
        }

        public LandingPage_SiteLinkConfiguration(string schema)
        {
            ToTable("SiteLink", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DisplayName).HasColumnName(@"DisplayName").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Directive).HasColumnName(@"Directive").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.Url).HasColumnName(@"URL").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Action).HasColumnName(@"Action").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Controller).HasColumnName(@"Controller").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.DisplayIcon).HasColumnName(@"DisplayIcon").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.IsDefault).HasColumnName(@"IsDefault").HasColumnType("bit").IsRequired();
            Property(x => x.IsEnabled).HasColumnName(@"IsEnabled").HasColumnType("bit").IsRequired();
            Property(x => x.Order).HasColumnName(@"Order").HasColumnType("int").IsOptional();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // SiteLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class MediaDashboard_SiteLinkConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MediaDashboard_SiteLink>
    {
        public MediaDashboard_SiteLinkConfiguration()
            : this("MediaDashboard")
        {
        }

        public MediaDashboard_SiteLinkConfiguration(string schema)
        {
            ToTable("SiteLink", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DisplayName).HasColumnName(@"DisplayName").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Directive).HasColumnName(@"Directive").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.Url).HasColumnName(@"URL").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Action).HasColumnName(@"Action").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Controller).HasColumnName(@"Controller").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.DisplayIcon).HasColumnName(@"DisplayIcon").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.IsDefault).HasColumnName(@"IsDefault").HasColumnType("bit").IsRequired();
            Property(x => x.IsEnabled).HasColumnName(@"IsEnabled").HasColumnType("bit").IsRequired();
            Property(x => x.IsPublic).HasColumnName(@"IsPublic").HasColumnType("bit").IsRequired();
            Property(x => x.Order).HasColumnName(@"Order").HasColumnType("int").IsOptional();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // BlogPost
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class MyHome_BlogPostConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MyHome_BlogPost>
    {
        public MyHome_BlogPostConfiguration()
            : this("MyHome")
        {
        }

        public MyHome_BlogPostConfiguration(string schema)
        {
            ToTable("BlogPost", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserId).HasColumnName(@"UserID").HasColumnType("int").IsRequired();
            Property(x => x.Image).HasColumnName(@"Image").HasColumnType("varbinary(max)").IsOptional();
            Property(x => x.Title).HasColumnName(@"Title").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.Body).HasColumnName(@"Body").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);

            // Foreign keys
            HasRequired(a => a.Security_User).WithMany(b => b.MyHome_BlogPosts).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // MyHome_BlogPost_UserID_Security_User_Id
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // BlogPostComment
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class MyHome_BlogPostCommentConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MyHome_BlogPostComment>
    {
        public MyHome_BlogPostCommentConfiguration()
            : this("MyHome")
        {
        }

        public MyHome_BlogPostCommentConfiguration(string schema)
        {
            ToTable("BlogPostComment", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserId).HasColumnName(@"UserID").HasColumnType("int").IsRequired();
            Property(x => x.CommentBody).HasColumnName(@"CommentBody").HasColumnType("varchar(max)").IsRequired().IsUnicode(false);
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);

            // Foreign keys
            HasRequired(a => a.Security_User).WithMany(b => b.MyHome_BlogPostComments).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // MyHome_BlogPostComment_UserID_Security_User_Id
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // SiteLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class MyHome_SiteLinkConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MyHome_SiteLink>
    {
        public MyHome_SiteLinkConfiguration()
            : this("MyHome")
        {
        }

        public MyHome_SiteLinkConfiguration(string schema)
        {
            ToTable("SiteLink", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserId).HasColumnName(@"UserID").HasColumnType("int").IsRequired();
            Property(x => x.DisplayName).HasColumnName(@"DisplayName").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Directive).HasColumnName(@"Directive").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.Url).HasColumnName(@"URL").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Action).HasColumnName(@"Action").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Controller).HasColumnName(@"Controller").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.DisplayIcon).HasColumnName(@"DisplayIcon").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.IsDefault).HasColumnName(@"IsDefault").HasColumnType("bit").IsRequired();
            Property(x => x.IsEnabled).HasColumnName(@"IsEnabled").HasColumnType("bit").IsRequired();
            Property(x => x.Image).HasColumnName(@"Image").HasColumnType("varbinary(max)").IsOptional();
            Property(x => x.Order).HasColumnName(@"Order").HasColumnType("int").IsOptional();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);

            // Foreign keys
            HasRequired(a => a.Security_User).WithMany(b => b.MyHome_SiteLinks).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // MyHome_SiteLink_UserID_Security_User_Id
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // UserConfig
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class MyHome_UserConfigConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<MyHome_UserConfig>
    {
        public MyHome_UserConfigConfiguration()
            : this("MyHome")
        {
        }

        public MyHome_UserConfigConfiguration(string schema)
        {
            ToTable("UserConfig", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.UserId).HasColumnName(@"UserID").HasColumnType("int").IsRequired();
            Property(x => x.ShowDateAndTime).HasColumnName(@"ShowDateAndTime").HasColumnType("bit").IsRequired();
            Property(x => x.ShowWeather).HasColumnName(@"ShowWeather").HasColumnType("bit").IsRequired();
            Property(x => x.ShowBanner).HasColumnName(@"ShowBanner").HasColumnType("bit").IsRequired();
            Property(x => x.ShowBookmarks).HasColumnName(@"ShowBookmarks").HasColumnType("bit").IsRequired();
            Property(x => x.ShowBlog).HasColumnName(@"ShowBlog").HasColumnType("bit").IsRequired();
            Property(x => x.BookmarksTitle).HasColumnName(@"BookmarksTitle").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.Greeting).HasColumnName(@"Greeting").HasColumnType("varchar(max)").IsRequired().IsUnicode(false);
            Property(x => x.BlogTitle).HasColumnName(@"BlogTitle").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.BackgroundImage).HasColumnName(@"BackgroundImage").HasColumnType("varbinary(max)").IsOptional();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);

            // Foreign keys
            HasRequired(a => a.Security_User).WithMany(b => b.MyHome_UserConfigs).HasForeignKey(c => c.UserId).WillCascadeOnDelete(false); // MyHome_UserHomeConfig_UserId_Security_User_ID
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // ContactLink
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_ContactLinkConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Portfolio_ContactLink>
    {
        public Portfolio_ContactLinkConfiguration()
            : this("Portfolio")
        {
        }

        public Portfolio_ContactLinkConfiguration(string schema)
        {
            ToTable("ContactLink", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.DisplayName).HasColumnName(@"DisplayName").HasColumnType("nvarchar").IsRequired().HasMaxLength(50);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Directive).HasColumnName(@"Directive").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.Url).HasColumnName(@"URL").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Action).HasColumnName(@"Action").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Controller).HasColumnName(@"Controller").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.DisplayIcon).HasColumnName(@"DisplayIcon").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.IsDefault).HasColumnName(@"IsDefault").HasColumnType("bit").IsRequired();
            Property(x => x.IsEnabled).HasColumnName(@"IsEnabled").HasColumnType("bit").IsRequired();
            Property(x => x.Order).HasColumnName(@"Order").HasColumnType("int").IsOptional();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // HighlightedSkill
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_HighlightedSkillConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Portfolio_HighlightedSkill>
    {
        public Portfolio_HighlightedSkillConfiguration()
            : this("Portfolio")
        {
        }

        public Portfolio_HighlightedSkillConfiguration(string schema)
        {
            ToTable("HighlightedSkill", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsRequired().HasMaxLength(500);
            Property(x => x.DisplayName).HasColumnName(@"DisplayName").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.ProficiencyPercentage).HasColumnName(@"ProficiencyPercentage").HasColumnType("int").IsOptional();
            Property(x => x.DisplayIcon).HasColumnName(@"DisplayIcon").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // LanguageSkill
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_LanguageSkillConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Portfolio_LanguageSkill>
    {
        public Portfolio_LanguageSkillConfiguration()
            : this("Portfolio")
        {
        }

        public Portfolio_LanguageSkillConfiguration(string schema)
        {
            ToTable("LanguageSkill", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.DisplayName).HasColumnName(@"DisplayName").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.ProficiencyPercentage).HasColumnName(@"ProficiencyPercentage").HasColumnType("int").IsOptional();
            Property(x => x.DisplayIcon).HasColumnName(@"DisplayIcon").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // PersonalDescription
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_PersonalDescriptionConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Portfolio_PersonalDescription>
    {
        public Portfolio_PersonalDescriptionConfiguration()
            : this("Portfolio")
        {
        }

        public Portfolio_PersonalDescriptionConfiguration(string schema)
        {
            ToTable("PersonalDescription", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Adjective1).HasColumnName(@"Adjective1").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.Adjective2).HasColumnName(@"Adjective2").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.Adjective3).HasColumnName(@"Adjective3").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.Blurb).HasColumnName(@"Blurb").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // Profile
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_ProfileConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Portfolio_Profile>
    {
        public Portfolio_ProfileConfiguration()
            : this("Portfolio")
        {
        }

        public Portfolio_ProfileConfiguration(string schema)
        {
            ToTable("Profile", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.FirstName).HasColumnName(@"FirstName").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.LastName).HasColumnName(@"LastName").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.DateOfBirth).HasColumnName(@"DateOfBirth").HasColumnType("datetime").IsRequired();
            Property(x => x.Address).HasColumnName(@"Address").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.PhoneNumber).HasColumnName(@"PhoneNumber").HasColumnType("nvarchar").IsRequired().HasMaxLength(25);
            Property(x => x.EmailAddress).HasColumnName(@"EmailAddress").HasColumnType("nvarchar").IsRequired().HasMaxLength(200);
            Property(x => x.PositionTitle).HasColumnName(@"PositionTitle").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.PersonalDescription).HasColumnName(@"PersonalDescription").HasColumnType("varchar").IsOptional().IsUnicode(false).HasMaxLength(500);
            Property(x => x.WebsiteText).HasColumnName(@"WebsiteText").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.WebsiteUrl).HasColumnName(@"WebsiteURL").HasColumnType("nvarchar").IsOptional().HasMaxLength(200);
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // Project
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_ProjectConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Portfolio_Project>
    {
        public Portfolio_ProjectConfiguration()
            : this("Portfolio")
        {
        }

        public Portfolio_ProjectConfiguration(string schema)
        {
            ToTable("Project", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Name).HasColumnName(@"Name").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsOptional().HasMaxLength(500);
            Property(x => x.Image).HasColumnName(@"Image").HasColumnType("varbinary(max)").IsOptional();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // ProjectType
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_ProjectTypeConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Portfolio_ProjectType>
    {
        public Portfolio_ProjectTypeConfiguration()
            : this("Portfolio")
        {
        }

        public Portfolio_ProjectTypeConfiguration(string schema)
        {
            ToTable("ProjectType", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Type).HasColumnName(@"Type").HasColumnType("nvarchar").IsRequired().HasMaxLength(100);
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // ProjectTypeMapping
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_ProjectTypeMappingConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Portfolio_ProjectTypeMapping>
    {
        public Portfolio_ProjectTypeMappingConfiguration()
            : this("Portfolio")
        {
        }

        public Portfolio_ProjectTypeMappingConfiguration(string schema)
        {
            ToTable("ProjectTypeMapping", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ProjectId).HasColumnName(@"ProjectID").HasColumnType("int").IsRequired();
            Property(x => x.ProjectTypeId).HasColumnName(@"ProjectTypeID").HasColumnType("int").IsRequired();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);

            // Foreign keys
            HasRequired(a => a.Portfolio_Project).WithMany(b => b.Portfolio_ProjectTypeMappings).HasForeignKey(c => c.ProjectId).WillCascadeOnDelete(false); // ProjectTypeMapping_ProjectID_Project_ID
            HasRequired(a => a.Portfolio_ProjectType).WithMany(b => b.Portfolio_ProjectTypeMappings).HasForeignKey(c => c.ProjectTypeId).WillCascadeOnDelete(false); // ProjectTypeMapping_ProjectTypeID_ProjectType_ID
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // TechSkill
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Portfolio_TechSkillConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Portfolio_TechSkill>
    {
        public Portfolio_TechSkillConfiguration()
            : this("Portfolio")
        {
        }

        public Portfolio_TechSkillConfiguration(string schema)
        {
            ToTable("TechSkill", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.Description).HasColumnName(@"Description").HasColumnType("nvarchar").IsRequired().HasMaxLength(500);
            Property(x => x.DisplayName).HasColumnName(@"DisplayName").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.ProficiencyPercentage).HasColumnName(@"ProficiencyPercentage").HasColumnType("int").IsOptional();
            Property(x => x.DisplayIcon).HasColumnName(@"DisplayIcon").HasColumnType("nvarchar").IsOptional().HasMaxLength(100);
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // __RefactorLog
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class RefactorLogConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<RefactorLog>
    {
        public RefactorLogConfiguration()
            : this("dbo")
        {
        }

        public RefactorLogConfiguration(string schema)
        {
            ToTable("__RefactorLog", schema);
            HasKey(x => x.OperationKey);

            Property(x => x.OperationKey).HasColumnName(@"OperationKey").HasColumnType("uniqueidentifier").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.None);
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            InitializePartial();
        }
        partial void InitializePartial();
    }

    // User
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.33.0.0")]
    public partial class Security_UserConfiguration : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<Security_User>
    {
        public Security_UserConfiguration()
            : this("Security")
        {
        }

        public Security_UserConfiguration(string schema)
        {
            ToTable("User", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"ID").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.ClientName).HasColumnName(@"ClientName").HasColumnType("nvarchar").IsRequired().HasMaxLength(500);
            Property(x => x.IsActive).HasColumnName(@"IsActive").HasColumnType("bit").IsRequired();
            Property(x => x.EmailAddress).HasColumnName(@"EmailAddress").HasColumnType("nvarchar").IsOptional().HasMaxLength(250);
            Property(x => x.IsAdmin).HasColumnName(@"IsAdmin").HasColumnType("bit").IsRequired();
            Property(x => x.UserName).HasColumnName(@"UserName").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Password).HasColumnName(@"Password").HasColumnType("nvarchar(max)").IsOptional();
            Property(x => x.Guid).HasColumnName(@"GUID").HasColumnType("uniqueidentifier").IsRequired();
            Property(x => x.CreatedOn).HasColumnName(@"CreatedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.CreatedBy).HasColumnName(@"CreatedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            Property(x => x.ModifiedOn).HasColumnName(@"ModifiedOn").HasColumnType("datetime").IsOptional();
            Property(x => x.ModifiedBy).HasColumnName(@"ModifiedBy").HasColumnType("varchar(max)").IsOptional().IsUnicode(false);
            InitializePartial();
        }
        partial void InitializePartial();
    }

    #endregion

}
// </auto-generated>

