  
/*
	This File is generated by the CategoryMaster.tt file written by mdoherty
	It is used to keep our Categories synchronized with the database
	If you add another Category save this template so we have up to date values
	
*/

using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;

namespace devinmajordotcom
{
    /// <summary>
    /// We need the ability to check for new HardwareTypes
    /// </summary>
	public static class DateRangeEnum
	{

		public enum DateRanges
		{
			[Display(Name="Last 60 Seconds")]
			Last60Seconds = 1,
			[Display(Name="Last 60 Minutes")]
			Last60Minutes = 2,
			[Display(Name="Last 24 Hours")]
			Last24Hours = 3,
			[Display(Name="Last 7 Days")]
			Last7Days = 4,
			[Display(Name="Last 30 Days")]
			Last30Days = 5,
		}
	}
}