CREATE TABLE SiteLinks (

	ID INT IDENTITY(1,1) NOT NULL,
	DisplayName NVARCHAR(50) NOT NULL,
	[URL] NVARCHAR(500) NOT NULL,
	DisplayIcon NVARCHAR(500) NULL,
	IsDefault BIT NOT NULL DEFAULT 0,
	IsEnabled BIT NOT NULL DEFAULT 1,
	IsAdminLink BIT NOT NULL DEFAULT 0,
	[Order] INT NULL,
	PRIMARY KEY (ID)

);